add log

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -53,11 +53,7 @@ jobs:
         allure_history: allure-history
     - name: Change status
       run: |
-        summary=$(grep -A 5 '"failed" : 0, "broken" : 0, "skipped" : 0' "$(pwd)/allure-report/widgets/summary.json")
-        echo "---"
-        echo "$summary"
-        echo "---"
-        [[ -n "$summary" ]] || echo "$summary"
+        summary=$(grep -A 5 '"failed" : 0, "broken" : 0, "skipped" : 0' "$(pwd)/allure-report/widgets/summary.json") || echo "not found"
     - name: Deploy report to Github Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v2
